version: '3.4'

services:
  master:
    image: ${DOCKER_REGISTRY-}master
    build:
      context: .
      dockerfile: Master/Dockerfile

  secondary:
    image: ${DOCKER_REGISTRY-}secondary
    build:
      context: .
      dockerfile: Secondary/Dockerfile

  secondary1:
    image: ${DOCKER_REGISTRY-}secondary
    build:
      context: .
      dockerfile: Secondary/Dockerfile

  secondary2:
    image: ${DOCKER_REGISTRY-}secondary
    build:
      context: .
      dockerfile: Secondary/Dockerfile