version: '3.4'

services:
  master:
    container_name: master
    image: ${DOCKER_REGISTRY-}master
    build:
      context: .
      dockerfile: Master/Dockerfile

  secondary:
    container_name: secondary
    image: ${DOCKER_REGISTRY-}secondary
    build:
      context: .
      dockerfile: Secondary/Dockerfile

  secondary1:
    container_name: secondary_1
    image: ${DOCKER_REGISTRY-}secondary
    build:
      context: .
      dockerfile: Secondary/Dockerfile

  secondary2:
    container_name: secondary_2
    image: ${DOCKER_REGISTRY-}secondary
    build:
      context: .
      dockerfile: Secondary/Dockerfile